version: '2'
services:

  # The Application
  app:
    build:
      context: ./build
      dockerfile: app.dockerfile
    working_dir: /usr/share/nginx
    volumes:
      - ./api/:/usr/share/nginx/api
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"

  # The Web Server
  web:
    build:
      context: ./build
      dockerfile: web.dockerfile
    working_dir: /usr/share/nginx
    volumes_from:
      - app
    ports:
      - "3000:3000"
      - "80:80"


  # The Database
  database:
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=howsy"
      - "MYSQL_USER=root"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
        - "33061:3306"

volumes:
  dbdata: